POST http://localhost:9000/user/admin/verify HTTP/1.1
Content-Type: application/json

{
    "userId": "eabb6d77-5d7b-46d4-8888-2e66e9d716ca",
    "hash": "TElTOFU4aWdabHloQzA2aWJhQ29Z"
}
###
POST http://localhost:9000/user/ HTTP/1.1
Content-Type: application/json

{
    "name": "Bob",
    "mobile": "+198382228711",
    "role": "developer"
}
###
GET http://localhost:9000/user/ HTTP/1.1
###
GET http://localhost:9000/user/61652b79d2ceaa9f44b262f5 HTTP/1.1
###
PATCH http://localhost:9000/user/61652b79d2ceaa9f44b262f5 HTTP/1.1
Content-Type: application/json

{
    "scope": "admin"
}
###
DELETE  http://localhost:9000/user/61652b79d2ceaa9f44b262f5 HTTP/1.1